### ISSUE TITLE
docker setup some problems

### ISSUE THREAD

**Issue by hozansahin** [linagora/tmail-backend#1170]
Hi There, 
https://github.com/linagora/tmail-flutter/blob/master/docker-compose.yaml
 I created my own docker-compose file using this directive and below is what worked.  On port 80 and 443 I need to use other different port where nginx works 
 my docker-compose.yaml
```
version: "3.9"
networks:
    1panel-network:
        external: true
services:
  tmail-frontend:
    image: linagora/tmail-web:master
    container_name: tmail-frontend
    ports:
      - "8180:80"
    volumes:
      - ./env.file:/usr/share/nginx/html/assets/env.file
    networks:
      - 1panel-network
    depends_on:
      - tmail-backend

  tmail-backend:
    image: linagora/tmail-backend:memory-branch-master
    container_name: tmail-backend
    volumes:
      - ./jwt_publickey:/root/conf/jwt_publickey
      - ./jwt_privatekey:/root/conf/jwt_privatekey
    ports:
      - "88:80"
    networks:
      - 1panel-network

```
My env.file
```
SERVER_URL=https://posta.thirdcode.org
DOMAIN_REDIRECT_URL=https://posta.thirdcode.org:3000
WEB_OIDC_CLIENT_ID=teammail-web
OIDC_SCOPES=openid,profile,email,offline_access
APP_GRID_AVAILABLE=supported
FCM_AVAILABLE=supported
IOS_FCM=supported
FORWARD_WARNING_MESSAGE=

```
I use cloudflare tunnel and my configuration is in the image below: 
![resim](https://github.com/user-attachments/assets/2dd8c11f-20a9-4965-9a47-04ec7894613f)

I cannot log in to any of the demo accounts. it gives a connection error. can you help with this.
