### ISSUE TITLE
[ALL-ATTACHMENTS] Apisix routes for all attchements feature

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#1471]
Need to add a new Apisix route in apisix.yaml file to allow requests to the new jmap downloadAll route

Maybe sth like (adapt to the platform if needed)

```
    id: jmap_download_all
    uri: /jmap/downloadAll/*
    service_id: jmap_service_oidc
    methods:
      - GET
      - OPTIONS
    plugin_config_id: jmap-plugin
    plugins:
      proxy-rewrite:
        headers:
          set:
            X-User-Secret: ${{X_USER_SECRET}}
```

Add to the basic helm chart too

Environments to update:

- [x] staging tenant-upn https://ci.linagora.com/linagora/lrs/saas/deployments/tmail/emaily-staging-apps/-/merge_requests/59
- [x] apisix helm chart: 1.0.12 https://ci.linagora.com/linagora/lrs/saas/tools/helm-charts/tmail-apisix/-/merge_requests/18/diffs
- [x] twp dev https://ci.linagora.com/linagora/lrs/saas/deployments/twake/twake-workplace-apps/-/merge_requests/299
- [x] twp staging https://ci.linagora.com/linagora/lrs/saas/deployments/twake/twake-workplace-apps/-/merge_requests/300
- [x] twp prod => https://ci.linagora.com/linagora/lrs/saas/deployments/twake/twake-workplace-apps/-/merge_requests/306
- [x] MU https://ci.linagora.com/linagora/lrs/saas/infrastructures/gov-mauritius/-/merge_requests/68
- [x] cnb staging => https://ci.linagora.com/linagora/lrs/saas/deployments/cnb/cnb-stg-ovh-apps/-/merge_requests/38
- [x] cnb prod => https://ci.linagora.com/linagora/lrs/saas/deployments/cnb/cnb-prd-ovh-apps/-/merge_requests/10
- [x] tmail.linagora.com
