### ISSUE TITLE
Integrate thumbnail in tmail docker-compose

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#599]
Integrate the thumbnail feature in tmail docker-compose

## How 
- Add `thumbnail server` container in docker-compose file 
```
services:
  thumbnail-server:
    container_name: linshare_thumbnail-server
    image: linagora/linshare-thumbnail-server:2.1.1
    ports:
      - "8088:8080"
```
- Add thumbnail configure file
