### ISSUE TITLE
[Apisix] ISSUE - Apisix forward the `Authorization` header to tmail-backend

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#688]
When I run tmail-backend with contain `JWTAuthenticationStrategy` 
I realized that Apisix forwards the `Authorization` in the header to Tmail, which makes the request authenticated FAIL

We should handle this case when running tmail-backend with more authentication strategy (not only XUser and Basic)

**Comment by vttranlina** [comment]
I tried with config:
```yaml
    plugins:
      proxy-rewrite:
        headers:
          remove:
            - Authorization
```

then this work, but we need to add it in all URI (a bit verbose) or find another way better
